### ISSUE TITLE
  File "site-packages\gooey\python_bindings\gooey_decorator.py", line 78, in <lambda>

### ISSUE THREAD

**Issue by coasterfr** [Zarxrax/png2srt#1]
Traceback (most recent call last):
  File "PNG2SRT.py", line 190, in <module>
  File "site-packages\gooey\python_bindings\gooey_decorator.py", line 78, in <lambda>
  File "PNG2SRT.py", line 187, in main
  File "PNG2SRT.py", line 139, in PNG2SRT
  File "PNG2SRT.py", line 115, in ocr_text
KeyError: 'responses'

I keep getting this error...

**Comment by Zarxrax** [comment]
KeyError probably means there is a problem with the google api key you are using. Please double check that you followed the instructions in the usage guide for creating the api key and then putting it into API_KEY.txt.

**Comment by coasterfr** [comment]
I've used it without problems some days ago for a few shows. After a few days I came back and it started giving this error. It goes thru 40 batches of images before giving this error. I'll look at the guide again to see if I made any mistakes with the api key but dont think so since it worked fine before...

On Mar 15, 2018 21:36, Zarxrax <notifications@github.com> wrote:

KeyError probably means there is a problem with the google api key you are using. Please double check that you followed the instructions in the usage guide for creating the api key and then putting it into API_KEY.txt.

**Comment by Zarxrax** [comment]
If starts to do part of the images and then breaks down, try reducing the "chunk" value.

**Comment by coasterfr** [comment]
thanks for the change, its working fine now
