### ISSUE TITLE
Fail to execute script

### ISSUE THREAD

**Issue by BobHD** [Zarxrax/png2srt#3]
Hi,

I get "Failed to execute script"
![error](https://user-images.githubusercontent.com/15735678/50225350-8e62c880-03a0-11e9-8db9-4835b9fe3472.gif)

**Comment by meganone** [comment]
Make sure the PNG and XML files are stored in a directory that has no Unicode characters. Solved it for me.

**Comment by BobHD** [comment]
Will do, thanks.
